// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SmartHome.Infrastructure;

#nullable disable

namespace SmartHome.Infrastructure.Migrations
{
    [DbContext(typeof(SmartHomeContext))]
    [Migration("20260927084427_InitialLab3")]
    partial class InitialLab3
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.12");

            modelBuilder.Entity("SmartHome.Infrastructure.Models.ClimateSensorModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double>("Humidity")
                        .HasColumnType("REAL");

                    b.Property<int>("RoomId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SerialNumber")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("RoomId")
                        .IsUnique();

                    b.ToTable("ClimateSensors");
                });

            modelBuilder.Entity("SmartHome.Infrastructure.Models.DeviceModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsOn")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("RoomId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("RoomId");

                    b.ToTable("Devices", (string)null);

                    b.UseTptMappingStrategy();
                });

            modelBuilder.Entity("SmartHome.Infrastructure.Models.RoomModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Rooms");
                });

            modelBuilder.Entity("SmartHome.Infrastructure.Models.ScenarioDeviceModel", b =>
                {
                    b.Property<int>("ScenarioId")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("DeviceId")
                        .HasColumnType("TEXT");

                    b.HasKey("ScenarioId", "DeviceId");

                    b.HasIndex("DeviceId");

                    b.ToTable("ScenarioDevices");
                });

            modelBuilder.Entity("SmartHome.Infrastructure.Models.ScenarioModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Scenarios");
                });

            modelBuilder.Entity("SmartHome.Infrastructure.Models.SmartLightModel", b =>
                {
                    b.HasBaseType("SmartHome.Infrastructure.Models.DeviceModel");

                    b.Property<int>("Brightness")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.ToTable("SmartLights", (string)null);
                });

            modelBuilder.Entity("SmartHome.Infrastructure.Models.ThermostatModel", b =>
                {
                    b.HasBaseType("SmartHome.Infrastructure.Models.DeviceModel");

                    b.Property<double>("CurrentTemperature")
                        .HasColumnType("REAL");

                    b.Property<string>("Mode")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("TargetTemperature")
                        .HasColumnType("REAL");

                    b.ToTable("Thermostats", (string)null);
                });

            modelBuilder.Entity("SmartHome.Infrastructure.Models.ClimateSensorModel", b =>
                {
                    b.HasOne("SmartHome.Infrastructure.Models.RoomModel", "Room")
                        .WithOne("ClimateSensor")
                        .HasForeignKey("SmartHome.Infrastructure.Models.ClimateSensorModel", "RoomId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Room");
                });

            modelBuilder.Entity("SmartHome.Infrastructure.Models.DeviceModel", b =>
                {
                    b.HasOne("SmartHome.Infrastructure.Models.RoomModel", "Room")
                        .WithMany("Devices")
                        .HasForeignKey("RoomId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Room");
                });

            modelBuilder.Entity("SmartHome.Infrastructure.Models.ScenarioDeviceModel", b =>
                {
                    b.HasOne("SmartHome.Infrastructure.Models.DeviceModel", "Device")
                        .WithMany("ScenarioDevices")
                        .HasForeignKey("DeviceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SmartHome.Infrastructure.Models.ScenarioModel", "Scenario")
                        .WithMany("ScenarioDevices")
                        .HasForeignKey("ScenarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Device");

                    b.Navigation("Scenario");
                });

            modelBuilder.Entity("SmartHome.Infrastructure.Models.SmartLightModel", b =>
                {
                    b.HasOne("SmartHome.Infrastructure.Models.DeviceModel", null)
                        .WithOne()
                        .HasForeignKey("SmartHome.Infrastructure.Models.SmartLightModel", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SmartHome.Infrastructure.Models.ThermostatModel", b =>
                {
                    b.HasOne("SmartHome.Infrastructure.Models.DeviceModel", null)
                        .WithOne()
                        .HasForeignKey("SmartHome.Infrastructure.Models.ThermostatModel", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SmartHome.Infrastructure.Models.DeviceModel", b =>
                {
                    b.Navigation("ScenarioDevices");
                });

            modelBuilder.Entity("SmartHome.Infrastructure.Models.RoomModel", b =>
                {
                    b.Navigation("ClimateSensor")
                        .IsRequired();

                    b.Navigation("Devices");
                });

            modelBuilder.Entity("SmartHome.Infrastructure.Models.ScenarioModel", b =>
                {
                    b.Navigation("ScenarioDevices");
                });
#pragma warning restore 612, 618
        }
    }
}
